---
routes:

    #########################################################
    # settlement / NODES                                          #
    #########################################################

    be_settlement:
        service:    settlement
        path:       /api/settlement
        pattern:    /api/settlement
        label:      settlement
        dscr:       A routegroup, no methods here.

    #########################################################
    # settlement / HEALTH                                         #
    #########################################################

    be_settlement_health_v1:
        pattern:    ${routes.be_settlement.path}/v1/health
        path:       ${routes.be_settlement.path}/v1/health
        label:      settlement health
        dscr:       A healthcheck endpoint for the microservice.
        service:    settlement
        provides:   health
        methods:
            get:    Glued\Controllers\ServiceController:health

  #########################################################
  # settlement / accounts and transactions                #
  #########################################################

    be_settlement_accounts_v1:
      pattern:    ${routes.be_settlement.path}/v1/accounts[/{uuid}]
      path:       ${routes.be_settlement.path}/v1/accounts
      label:      Settlement accounts
      dscr:       Accounts (banking, cash, virtual) 
      service:    settlement
      methods:
        get:     Glued\Controllers\ServiceController:accounts_r1
        post:    Glued\Controllers\ServiceController:accounts_c1

    be_settlement_transactions_v1:
      pattern:    ${routes.be_settlement.path}/v1/transactions[/{account}/{trx}]
      path:       ${routes.be_settlement.path}/v1/transactions
      label:      Transactions
      dscr:       Transactions (banking, cash, virtual) relevant to a setllement accline.
      service:    settlement
      methods:
        get:     Glued\Controllers\ServiceController:transactions_r1
        post:    Glued\Controllers\ServiceController:transactions_c1
